# Generated by Django 5.0.2 on 2024-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
