# Generated by Django 5.0.2 on 2024-03-01 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0002_appuser_is_active_appuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="appuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
