# Generated by Django 5.0.2 on 2024-03-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0003_remove_appuser_is_staff_appuser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
