# Generated by Django 5.0.2 on 2024-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0004_appuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="avatar",
            field=models.ImageField(default="media/default.png", upload_to="media/"),
        ),
    ]
